global:
  component: &component backend
  environment: &environment prod
  deployment: &deployment prod
  owner: &owner dev

  image:
    repository: 184689117095.dkr.ecr.eu-central-1.amazonaws.com/dev-backend-prod
    tag: prod # To be overwritten with SHA by ArgoCD
  ingress:
    domains:
      - roo777.com
      - roob048.com
      - roob073.com
      - roob312.com
      - roob313.com
      - roob4.com
      - roob537.com
      - roob635.com
      - roob738.com
      - roob749.com
      - roob836.com
      - roobet.com
      - roobet.party
      - prod.roobet.systems
  labels:
    component: *component
    deployment: *deployment
    environment: *environment
    owner: *owner
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 2Gi

  configs:
    APP: atlanta
    AWS_DEFAULT_REGION: us-east-2
    BACKEND_BASE: https://roobet.com/_api
    BET_MAX_PROFIT: "1000000"
    BLOCKIO_BITCOIN_POOLING_ADDRESS: bc1qg83pyg47edqd4jdu6vyjjcq3dahv68hpnwzpmvj53y44sv9vc75qdf2vpp
    BLOCKIO_BITCOIN_WITHDRAWAL_ADDRESS: bc1qg83pyg47edqd4jdu6vyjjcq3dahv68hpnwzpmvj53y44sv9vc75qdf2vpp
    BLOCKIO_DOGECOIN_POOLING_ADDRESS: A49pbRXLq5J5GTuiKsTQq3ov4YJz2xJD9G
    BLOCKIO_DOGECOIN_WITHDRAWAL_ADDRESS: A49pbRXLq5J5GTuiKsTQq3ov4YJz2xJD9G
    BLOCKIO_LITECOIN_POOLING_ADDRESS: ltc1q6gygermkdllq0ywxwaxj00shegvpg5trng2kdrkdxzgqwsrrd2fslu8l77
    BLOCKIO_LITECOIN_WITHDRAWAL_ADDRESS: ltc1q6gygermkdllq0ywxwaxj00shegvpg5trng2kdrkdxzgqwsrrd2fslu8l77
    CASH_DASH_MAX_BET: "20000"
    CASH_DASH_MAX_PAYOUT: "150000"
    COINFLIP_MAX_BET: "200000"
    DATADOG_SAMPLE_RATE: "0.01"
    ENVIRONMENT: production
    ETHEREUM_HTTP_ARCHIVE_PROVIDER: https://ultra-dry-water.quiknode.pro/e92e37e37a8025f59e51794c34b20fb22c3ee651/
    ETHEREUM_HTTP_PROVIDER: https://ultra-dry-water.quiknode.pro/e92e37e37a8025f59e51794c34b20fb22c3ee651/
    ETHEREUM_WS_PROVIDER: ""
    FRONTEND_BASE: https://roobet.com
    HACKSAW_BASE_URL: https://api.hacksawgaming.com/api
    HOTBOX_GAME_COUNT: "2000000"
    HOTBOX_MAX_BET: "75000"
    HUB88_API_URL: https://api.hub88.io
    HUB88_SUB_PARTNER_ID: roobet2
    JUNGLE_MINES_MAX_PAYOUT: "150000"
    LINEAR_MINES_MAX_BET: "20000"
    LINEAR_MINES_MAX_PAYOUT: "150000"
    MEDIA_DEST_PUBLIC_IMAGES_BUCKET: roobet-public
    MINES_MAX_PAYOUT: "150000"
    MODE: prod
    MOONPAY_BASE_URL: https://buy.moonpay.com/?apiKey=
    PLINKO_GAME_COUNT: "100000"
    PRAGMATIC_API_DOMAIN: api-dk7.pragmaticplay.net
    PRAGMATIC_STYLENAME: tekh_roobet
    RABBITMQ_HEARTBEAT: "10"
    RAINS_DEFAULT_DURATION: "1"
    REDIS_HOST: 35.242.233.176
    REDIS_PORT: "6379"
    REDIS_SECONDARY_URL: rediss://master.sre-redis-prod.hil9l4.euc1.cache.amazonaws.com:6379
    REDIS_SYNC_ENABLED: false
    REPORTING_AS_JOBS: true
    REPORTING_BUCKET: roobet-admin-reports
    REPORTING_USER_BALANCES_ENDPOINT: https://reports.xcm.cw/settlement/api/www.roobet.com/files/a2b2832a-7563-4544-ad20-cfd014202445
    RETHINKDB_DB: atlanta
    RETHINKDB_HOST: rethinkdb-proxy.rethinkdb
    RETHINKDB_USER: admin
    RIPPLE_DEST_TAG_INIT: "2023"
    RIPPLE_HTTP_PROVIDER: https://light-white-valley.xrp-mainnet.quiknode.pro/e5bd37bdaacc0f198973bea18a62b02d637cc6d3/
    RIPPLE_WS_PROVIDER: wss://light-white-valley.xrp-mainnet.quiknode.pro/e5bd37bdaacc0f198973bea18a62b02d637cc6d3/
    SLOTEGRATOR_CURRENCY: USD
    SLOTEGRATOR_SLOTS_BASE_URL: https://gis.slotegrator.com/api/index.php/v1
    SLOTEGRATOR_SPORTS_BASE_URL: https://bet.stgr.pw/api/v1
    SLOTEGRATOR_SPORTS_SPORTSBOOK_UUID: d595248f-75ff-454b-8d6d-e6a232dff199
    SOFTSWISS_CASINO_ID: roobet
    SOFTSWISS_GCP_URL: https://casino.cur.a8r.games
    SOFTSWISS_RETURN_URL: https://roobet.com
    TOWERS_MAX_PAYOUT: "150000"
    TRON_HTTP_PROVIDER: https://holy-boldest-county.tron-mainnet.quiknode.pro/03795410a748eba5c34e37803867134f96684d18
    TRON_WS_PROVIDER: ""
    VERIFICATION_STORAGE_BUCKET: roobet-user-documents
    WEBHOOK_BASE: https://shield.gandalf.pw
    WEBSOCKET_BASE: wss://api.roobet.com
    WEBSOCKET_GQL_ADMIN_PORT: "8088"
    WEBSOCKET_GQL_PRODUCT_PORT: "8087"
    WEBSOCKET_HOST: api.roobet.com

  secrets:
    - ALCHEMY_API_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - BIGQUERY_CREDENTIALS
    - BIGQUERY_PROJECT_ID
    - BLOCKCYPHER_TOKEN
    - BLOCKIO_API_SECRET
    - BLOCKIO_BITCOIN_KEY
    - BLOCKIO_DOGECOIN_KEY
    - BLOCKIO_LITECOIN_KEY
    - BLOCKIO_PIN
    - CASH_DASH_SEED
    - CHAINALYSIS_TOKEN
    - COINBASE_API_KEY
    - COINBASE_API_SECRET
    - COINFLIP_SEED
    - CRASH_SALT
    - CRASH_SEED
    - DICE_SEED
    - EMBER_DECRYPTION_KEY
    - ETH_MNEMONIC
    - ETH_SECRET_INDEX
    - ETH_SECRET
    - ETHERSCAN_API_KEY
    - FACEBOOK_CLIENT_ID
    - FACEBOOK_CLIENT_SECRET
    - FASTTRACK_SECRET
    - FIXER_API_KEY
    - GOOGLE_API_KEY
    - GOOGLE_APPLICATION_CREDENTIALS
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - GOOGLE_PRIVATE_KEY
    - GOOGLE_SERVICE_ACCOUNT_EMAIL
    - HACKSAW_API_PASSWORD
    - HACKSAW_API_USERNAME
    - HACKSAW_PARTNER_ID
    - HACKSAW_SECRET
    - HOTBOX_SALT
    - HOTBOX_SEED
    - HUB88_API_PUBLIC_KEY
    - HUB88_OPERATOR_ID
    - HUB88_PRIVATE_KEY
    - HUB88_PUBLIC_KEY
    - INTERCOM_TOKEN
    - INTERCOM_USER_HASH_SECRET
    - JUNGLE_MINES_SEED
    - JWT_SECRET
    - LINEAR_MINES_SEED
    - MAILGUN_KEY
    - MEGALOMONGO_ANALYTICS_URI
    - MEGALOMONGO_URI
    - MINES_SEED
    - MONGO_ANALYTICS_URI
    - MONGODB_URI
    - MOONPAY_CLIENT_KEY
    - MOONPAY_SECRET_KEY
    - PAGERDUTY_TOKEN
    - PAYMENTIQ_MERCHANT_ID
    - PAYMENTIQ_PRIVATE_KEY
    - PLAYNGO_ACCESS_TOKEN
    - PLINKO_SALT
    - PLINKO_SEED
    - PRAGMATIC_SECRET_KEY
    - PRAGMATIC_SECURE_LOGIN
    - RABBITMQ_CONSUMER_URI
    - RABBITMQ_PRODUCER_URI
    - RECAPTCHA_SECRET
    - RECAPTCHA_V3_SECRET
    - REDIS_PASS
    - REDIS_SECONDARY_PASS
    - REDTIGER_API_KEY
    - REDTIGER_RECON_TOKEN
    - REPORTING_USER_BALANCES_KEY
    - RETHINKDB_USER
    - RIPPLE_SECRET
    - ROULETTE_SALT
    - ROULETTE_SEED
    - SEON_API_KEY
    - SEON_PASSWORD_SALT
    - SESSION_SECRET
    - SHUFTI_CLIENT_ID
    - SHUFTI_SECRET_KEY
    - SLOTEGRATOR_SLOTS_MERCHANT_ID
    - SLOTEGRATOR_SLOTS_MERCHANT_KEY
    - SLOTEGRATOR_SPORTS_MERCHANT_ID
    - SLOTEGRATOR_SPORTS_MERCHANT_KEY
    - SMARTY_AUTH_ID
    - SMARTY_AUTH_TOKEN
    - SOFTSWISS_AUTH_TOKEN
    - SOFTSWISS_WALLET_URL
    - SPLASH_TECH_PRIVATE_KEY
    - TOWERS_SEED
    - TRON_MAIN_WALLET_MNEMONIC
    - TRON_POOLING_WALLET_MNEMONIC
    - TRON_USER_WALLET_MNEMONIC
    - TWILIO_AUTH_TOKEN
    - TWILIO_SID
    - TWILIO_VERIFY_SERVICE_SID
    - UNIBO_PASSWORD
    - UNIBO_USERNAME
    - USER_EXPORT_TOKEN
