global:
  component: &component backend
  environment: &environment non-prod
  deployment: &deployment stage
  owner: &owner dev

  image:
    repository: 461710506523.dkr.ecr.eu-central-1.amazonaws.com/dev-backend-non-prod
    tag: stage # To be overwritten with SHA by ArgoCD
  ingress:
    domains:
      - 777.dev
      - non-prod.roobet.systems
  labels:
    component: *component
    deployment: *deployment
    environment: *environment
    owner: *owner

  configs:
    BACKEND_BASE: https://api.777.dev
    BLOCKIO_BITCOIN_POOLING_ADDRESS: 2N1F3aApM7dEj28fmv1m2k1HcB7A3k1AXEh
    BLOCKIO_BITCOIN_WITHDRAWAL_ADDRESS: 2N1F3aApM7dEj28fmv1m2k1HcB7A3k1AXEh
    BLOCKIO_DOGECOIN_POOLING_ADDRESS: 2NCEz9jRKn16bvktJC1kQLSP5o38d8VjSPN
    BLOCKIO_DOGECOIN_WITHDRAWAL_ADDRESS: 2NCEz9jRKn16bvktJC1kQLSP5o38d8VjSPN
    BLOCKIO_LITECOIN_POOLING_ADDRESS: QTfSjamLyQJFFxPV9JUXjia5AC1iEmkvTv
    BLOCKIO_LITECOIN_WITHDRAWAL_ADDRESS: QTfSjamLyQJFFxPV9JUXjia5AC1iEmkvTv
    ENVIRONMENT: staging
    ETHEREUM_HTTP_ARCHIVE_PROVIDER: ''
    ETHEREUM_HTTP_PROVIDER: https://young-patient-wind.ethereum-goerli.quiknode.pro/b202ff6e192de6fb7eaf9855fe2afb477f462ee4/
    ETHEREUM_WS_PROVIDER: wss://young-patient-wind.ethereum-goerli.quiknode.pro/b202ff6e192de6fb7eaf9855fe2afb477f462ee4/
    FRONTEND_BASE: https://777.dev
    HACKSAW_BASE_URL: https://api-stg.hacksawgaming.com/api
    HUB88_API_URL: https://api.server1.ih.testenv.io
    HUB88_SUB_PARTNER_ID: roobet2
    MEDIA_DEST_PUBLIC_IMAGES_BUCKET: roobet-dev-public
    MODE: staging
    MOONPAY_BASE_URL: https://buy-sandbox.moonpay.com/?apiKey=
    PRAGMATIC_API_DOMAIN: api.prerelease-env.biz
    PRAGMATIC_STYLENAME: tekh_roobetstage2
    REDIS_URL: rediss://master.sre-redis-non-prod.mbh8cp.euc1.cache.amazonaws.com:6379
    REPORTING_BUCKET: roobet-dev-admin-reports
    REPORTING_USER_BALANCES_ENDPOINT: https://api.777.dev
    RETHINKDB_DB: atlanta-staging
    RETHINKDB_HOST: rethinkdb-proxy.rethinkdb
    RETHINKDB_USER: admin
    RIPPLE_DEST_TAG_INIT: '2023'
    RIPPLE_HTTP_PROVIDER: https://polished-convincing-patina.xrp-testnet.discover.quiknode.pro/63bb51a3a76932df08005d86ade82ebad3f5bab9/
    RIPPLE_WS_PROVIDER: wss://polished-convincing-patina.xrp-testnet.discover.quiknode.pro/63bb51a3a76932df08005d86ade82ebad3f5bab9/
    SLOTEGRATOR_SLOTS_BASE_URL: https://staging.slotegrator.com/api/index.php/v1
    SLOTEGRATOR_SPORTS_BASE_URL: https://bet.ga-stage.work/api/v1
    SLOTEGRATOR_SPORTS_SPORTSBOOK_UUID: d595248f-75ff-454b-8d6d-e6a232dff199
    SOFTSWISS_CASINO_ID: roobet_stg
    SOFTSWISS_GCP_URL: https://casino.int.a8r.games
    SOFTSWISS_RETURN_URL: https://777.dev
    TRON_HTTP_PROVIDER: https://empty-fabled-arm.tron-mainnet.quiknode.pro/b798178523734bad6f54a35fd835f892afc434f7
    TRON_WS_PROVIDER: wss://empty-fabled-arm.tron-mainnet.quiknode.pro/b798178523734bad6f54a35fd835f892afc434f7
    VERIFICATION_STORAGE_BUCKET: roobet-staging-user-documents
    WEBHOOK_BASE: https://api.777.dev
    WEBSOCKET_BASE: wss://api.777.dev
    WEBSOCKET_GQL_ADMIN_PORT: '8088'
    WEBSOCKET_GQL_PRODUCT_PORT: '8087'
    WEBSOCKET_HOST: api.777.dev
    YGGDRASIL_ENABLED: true
    YGGDRASIL_API_BASE_URL: https://integration.stage-ygg.com/api/v1
    YGGDRASIL_SESSION_KEY_EXPIRATION: "5 minutes"
    YGGDRASIL_LAUNCH_INTENT: "test"
    YGGDRASIL_LAUNCH_REGION: "malta"
    YGGDRASIL_LAUNCH_ORG: "roobet"

  secrets:
    - ALCHEMY_API_KEY
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - BIGQUERY_CREDENTIALS
    - BIGQUERY_PROJECT_ID
    - BLOCKCYPHER_TOKEN
    - BLOCKIO_API_SECRET
    - BLOCKIO_BITCOIN_KEY
    - BLOCKIO_DOGECOIN_KEY
    - BLOCKIO_LITECOIN_KEY
    - BLOCKIO_PIN
    - CASH_DASH_SEED
    - CHAINALYSIS_TOKEN
    - COINBASE_API_KEY
    - COINBASE_API_SECRET
    - COINFLIP_SEED
    - CRASH_SALT
    - CRASH_SEED
    - DICE_SEED
    - EMBER_DECRYPTION_KEY
    - ETH_MNEMONIC
    - ETH_SECRET_INDEX
    - ETH_SECRET
    - ETHERSCAN_API_KEY
    - FACEBOOK_CLIENT_ID
    - FACEBOOK_CLIENT_SECRET
    - FASTTRACK_SECRET
    - FIXER_API_KEY
    - GOOGLE_API_KEY
    - GOOGLE_APPLICATION_CREDENTIALS
    - GOOGLE_CLIENT_ID
    - GOOGLE_CLIENT_SECRET
    - GOOGLE_PRIVATE_KEY
    - GOOGLE_SERVICE_ACCOUNT_EMAIL
    - HACKSAW_API_PASSWORD
    - HACKSAW_API_USERNAME
    - HACKSAW_PARTNER_ID
    - HACKSAW_SECRET
    - HOTBOX_SALT
    - HOTBOX_SEED
    - HUB88_API_PUBLIC_KEY
    - HUB88_OPERATOR_ID
    - HUB88_PRIVATE_KEY
    - HUB88_PUBLIC_KEY
    - INTERCOM_TOKEN
    - INTERCOM_USER_HASH_SECRET
    - JUNGLE_MINES_SEED
    - JWT_SECRET
    - LINEAR_MINES_SEED
    - MAILGUN_KEY
    - MEGALOMONGO_URI
    - MINES_SEED
    - MONGODB_URI
    - MOONPAY_CLIENT_KEY
    - MOONPAY_SECRET_KEY
    - PAGERDUTY_TOKEN
    - PAYMENTIQ_MERCHANT_ID
    - PAYMENTIQ_PRIVATE_KEY
    - PLAYNGO_ACCESS_TOKEN
    - PLINKO_SALT
    - PLINKO_SEED
    - PRAGMATIC_SECRET_KEY
    - PRAGMATIC_SECURE_LOGIN
    - RABBITMQ_CONSUMER_URI
    - RABBITMQ_PRODUCER_URI
    - RECAPTCHA_SECRET
    - RECAPTCHA_V3_SECRET
    - REDIS_PASS
    - REDTIGER_API_KEY
    - REDTIGER_RECON_TOKEN
    - REPORTING_USER_BALANCES_KEY
    - RETHINKDB_USER
    - RIPPLE_SECRET
    - ROULETTE_SALT
    - ROULETTE_SEED
    - SEON_API_KEY
    - SEON_PASSWORD_SALT
    - SESSION_SECRET
    - SHUFTI_CLIENT_ID
    - SHUFTI_SECRET_KEY
    - SLACK_CHANNEL_OVERRIDE
    - SLOTEGRATOR_SLOTS_MERCHANT_ID
    - SLOTEGRATOR_SLOTS_MERCHANT_KEY
    - SLOTEGRATOR_SPORTS_MERCHANT_ID
    - SLOTEGRATOR_SPORTS_MERCHANT_KEY
    - SMARTY_AUTH_ID
    - SMARTY_AUTH_TOKEN
    - SOFTSWISS_AUTH_TOKEN
    - SOFTSWISS_WALLET_URL
    - SPLASH_TECH_PRIVATE_KEY
    - TOWERS_SEED
    - TRON_MAIN_WALLET_MNEMONIC
    - TRON_POOLING_WALLET_MNEMONIC
    - TRON_USER_WALLET_MNEMONIC
    - TWILIO_AUTH_TOKEN
    - TWILIO_SID
    - TWILIO_VERIFY_SERVICE_SID
    - UNIBO_PASSWORD
    - UNIBO_USERNAME
    - USER_EXPORT_TOKEN
