global:
  apm:
    enabled: true
  ingress:
    enabled: true
  metrics:
    enabled: true
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi

app:
  name: api-public
  type: deployment

  ip2location: true
  replicas: 1
  service: true
  paths:
    - /affiliate/stats
    - /tipping/send
