global:
  apm:
    enabled: true
  ingress:
    enabled: true
  metrics:
    enabled: true
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi

app:
  name: api
  type: deployment

  ip2location: true
  replicas: 3
  service: true
  paths:
    - /
