global:
  configs: null
  image:
    repository: 184689117095.dkr.ecr.eu-central-1.amazonaws.com/dev-alpine-prod
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi
  secrets: null
  serviceAccount:
    enabled: true
    resources: '["deployments", "externalsecrets"]'
    verbs: '["get", "list", "patch", "update", "watch"]'

app:
  name: config-secrets-rollout
  type: cronjob
  
  additionalSecrets:
    - BIGQUERY_PROJECT_ID # Secrets can't be empty for now
  command: '["/bin/sh", "-c", "/opt/bin/configsecretsrollout.sh"]'
  image:
    tag: prod
  schedule: '0 0 31 2 *' # Fake date (Feb 31) so it never runs automatically, just exists to be run manually
  scripts:
    configsecretsrollout.sh: /opt/bin
