{{- range .Values.app.workers | default (list $.Values.app.name) -}}
{{- $Values := mergeOverwrite (deepCopy $.Values) (index $.Values .) (dict "app" (dict "name" .)) -}}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "app.lowerName" $Values }}
  labels:
    {{- include "app.labels" $Values | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-parameter-store
  target:
    creationPolicy: Owner
    name: {{ template "app.lowerName" $Values }}
  data:
    {{- template "app.secrets" $Values }}

---
{{ end }}
